export const ADD = 'ADD_CARLISTING';
export const ADD_SUCCESS = 'ADD_CARLISTING_SUCCESS';
export const ADD_FAILED = 'ADD_CARLISTING_FAILED';

export const GET = 'GET_CARLISTING';
export const GET_SUCCESS = 'GET_CARLISTING_SUCCESS';
export const GET_FAILED = 'GET_CARLISTING_FAILED';

export const GET_COLLECTION = 'GET_COLLECTION_CARLISTING';
export const GET_COLLECTION_SUCCESS = 'GET_COLLECTION_CARLISTING_SUCCESS';
export const GET_COLLECTION_FAILED = 'GET_COLLECTION_CARLISTING_FAILED';


export const GET_ID = 'GET_ID_CARLISTING';
export const GET_ID_SUCCESS = 'GET_ID_CARLISTING_SUCCESS';
export const GET_ID_FAILED = 'GET_ID_CARLISTING_FAILED';
